ethereum-optimism/community-hub

src/docs/integration.md
@maurelian Implemented quick-fixes from #7 . Questions still need to be resolved
=> Improving integration docs for issue#7

src/docs/integration.md, src/docs/protocol.md
Added "L1 and L2 communcation" section to integration docs.
=> added L1 and L2 comms section

src/docs/integration.md
Turned note into a dropdown, if user wants to view old docs
=> quick add of container

src/.vuepress/config.js, src/.vuepress/styles/index.styl, src/docs/fees.md
This one was requested on discord.
=> Add a small page explaining transaction fees

src/tutorial/README.md
=> Added Yarn 1.x to Prereq Software

src/docs/protocol/protocol.md
Adds specifics about what should, and should not be allowed.
=> Expand documentation on Safety Checker

src/.vuepress/components/Home.vue, src/.vuepress/config.js
=> add: link to GH on header and per page

src/faqs/README.md
Fixes dead link to the EVM/OVM comparison page in FAQs
=> fix:  broken link

README.md, src/docs/resources/tutorials.md
You are linking to non-https optimisim.io sites.  They are currently not forwarding http -> https, so you were directing people to insecure sites.
**Metadata**
=> Fix http links

README.md
=> chore: add socials and preface

src/docs/developers/dev-dump.md, src/docs/resources/talks.md, src/docs/resources/tooling.md, src/docs/resources/tutorials.md
=> added tuts and examples to tuts page

src/docs/resources/tutorials.md
=> remove: outdated guide

src/docs/developers/integration.md
=> chore: corrected to the new monorepo

src/docs/developers/integration.md
There was a diagram that was incorrect in the integration docs
=> remove:  incorrect diagram

src/docs/developers/integration.md
=> Correct deposit-withdraw example to new example repository

src/docs/developers/integration.md
=> fix: line break

src/docs/resources/tutorials.md
=> remove: outdated tuts

src/docs/developers/integration.md
Just a small typo on the documentation
=> Fix typo on integration.md

src/docs/developers/integration.md
Fix @eth-optimism/hardhat-ovm typo and link in integration.md
**Metadata**
=> Fix @eth-optimism/hardhat-ovm broken link

src/docs/developers/integration.md
=> fix: incorrect websocket endpoint

src/docs/resources/tutorials.md
=> fix: broken links

src/.vuepress/components/Home.vue, src/.vuepress/config.js, src/.vuepress/styles/index.styl, src/testnet/README.md
Adds a new `testnet` page so that it's easier to find information about our testnet.
=> feat: add testnet page

src/docs/developers/bridging.md, src/docs/protocol/protocol.md
Updates the standard bridge documentation.
=> Update standard bridge documentation

src/docs/developers/eth-gateway.md
Update the Layer `OVM_L1ETHGateway` resides on
=> Update the Layer `OVM_L1ETHGateway` resides on

src/docs/developers/eth-gateway.md
Expands slightly on text in the introduction, as per feedback in #124.
=> tweak: minor update to gateway guide

src/docs/README.md
Fix typo in the Welcome page
Text saying "We're working on a TL;DR page for just you." should be changed to "We're working on a TL;DR page _just for you_.".
**Metadata**
=> Fix typo in the Welcome page

src/.vuepress/config.js, src/.vuepress/styles/index.styl, src/faqs/README.md
Updates the FAQ page with the latest rewrite.
=> feat: add new FAQ page

src/docs/developers/l2/dev-node.md
Added a link from the dev node page to the RPC page
=> Add a link to the RPC page to this page

src/.vuepress/config.js
Modify the Table of Content to remove *coming soon* from Elena's completed tutorials.
=> Add erc20 to toc

src/docs/developers/util.md
As requested in the `lyra-finance` Discord channel,
OP-1150
=> Added how to do Multisig

src/docs/developers/l2/dev-node.md
This is much faster than compiling and building them yourself (and those instructions are still there, of course)
=> Instructions to download images

src/docs/protocol/protocol.md
Some links on the contracts overview page were broken.
=> Fix broken links to account contracts

src/docs/developers/l2/deploy.md
Adds criteria for upcoming whitelisting wave
=> Add Whitelist Criteria

src/.vuepress/config.js, src/docs/developers/l2/deploy.md
=> Add to table of contents and clean up wording

src/docs/developers/l2/deploy.md
Just clarifies more specificity around what we need for CREATE2 forwards compatibility with uniswap.
=> update CREATE2 language

src/docs/developers/l2/convert.md, src/docs/infra/third-party-tools.md
1. Closing INT-88 
2. A few updates in convert.md
=> Update Tenderly in 3rd party tools

src/.vuepress/config.js, src/docs/developers/l2/remix.md
Closing ENG-1084
https://remix-optimism-compiler-plugin.readthedocs.io/en/latest/
=> Turns out the remix instructions are already written

src/.vuepress/styles/index.styl, src/docs/developers/talks.md, src/docs/users/apps.md, src/docs/users/gateway.md
* Changed logos from `height:50` to `max-height:50`
* Added the list of tokens to the gateway
* Closing INT-106
=> Made apps.md presentable on cell phones

src/docs/protocol/evm-comparison.md
This PR fixes a broken link to the OVM Account implementation.
=> Update evm-comparison.md fixing broken link

src/docs/users/metamask.md
Update 2 dead links connecting to Optimism's networks page
**Metadata**
- Fixes #[https://community.optimism.io/docs/users/metamask.html#connecting-manually]
=> Update dead Networks links

src/docs/users/apps.md
Updated Rubicon description and added links to some Rubicon resources.
Added an updated Rubicon description from our team and added links to some Rubicon resources.
=> Updated Rubicon Description

src/docs/developers/l2/changeset.md
Added a missing "s" to transfer.
=> Just fixing a typo :)

src/docs/developers/l2/contracts-2.0.md, src/docs/developers/l2/new-fees.md, src/docs/users/fees-2.0.md
See PR #204  for list of issues
=> Elena changes for PR #204

src/.vuepress/config.js, src/docs/users/deposit.md
=> Added a page about the different options to get ETH into L2

src/.vuepress/config.js, src/docs/developers/l2/convert-2.0.md, src/docs/developers/l2/convert.md
Removed most material, which is no longer relevant, and added the new opcodes.
Closing: INT-130
=> Added the convert 2.0 page

src/.vuepress/config.js, src/docs/protocol/sequencing.md
Adds sequencing documentation.
**Metadata**
- Fixes INT-195
- Fixes INT-196
- Fixes INT-197
=> feat(docs): sequencing docs

src/docs/protocol/sequencing.md
=> Fixed a typo in sequencing.md

src/docs/developers/l2/convert-2.0.md
Used Liam's snippet from
https://twitter.com/liamihorne/status/1437168861846069254?s=21
=> Added how to connect a user's wallet to OE programatically

src/.vuepress/config.js, src/docs/developers/l2/hardhat.md, src/docs/developers/l2/tooling-2.0.md, src/docs/developers/l2/truffle.md, src/docs/infra/networks.md
Also update the other tooling pages to say they are OVM 1.0.
Closing: INT-129
=> Updated the tooling for OVM 2.0 (where there isn't much to do)

src/.vuepress/config.js, src/docs/protocol/fraud-proofs.md
Adds a quick explainer on fraud proofs and implications on users.
**Metadata**
- Fixes INT-199
- Fixes INT-200
=> feat(docs): security & challenge explainer docs

src/.vuepress/config.js
(for the retro-funding public goods section)
Closing: INT-266
=> Move OVM 1.0 docs to a separate section

src/docs/developers/l2/convert-2.0.md, src/docs/developers/l2/dev-node.md
Approved by Francisco Giordano of OpenZeppelin (the person who requested this additional content)
Closing: INT-273
=> Updates about the Development Node

src/docs/developers/l2/block-time.md
=> Changed block-time.md to fit OVM 2.0

src/docs/users/getting-started.md
"Typically between a 1% and 10% of of the cost on L1."
=> "Typically between a 1% and 10% of the cost on L1."
=> removed extra 'of'

src/docs/developers/l2/convert-2.0.md, src/docs/protocol/protocol-2.0.md
With the new release, no longer experimental :)
=> fix(docs): update experimental branch now merged to master

src/docs/developers/util.md
As discussed with Uma on discord
=> Explained the WETH contract better

src/docs/developers/bridge/standard-bridge.md
* [`OVM_L1StandardBridge`](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1StandardBridge.sol) => https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/L1/messaging/L1StandardBridge.sol
* [`OVM_L2StandardBridge`](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardBridge.sol) => https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/L2/messaging/L2StandardBridge.sol
* [`IL2StandardERC20`](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/optimistic-ethereum/libraries/standards/IL2StandardERC20.sol) => …
=> Updating dead links

src/docs/developers/l2/deploy.md
change link to https://optimismpbc.typeform.com/onboard
=> fix link to whitelist form

src/docs/developers/util.md
(they answered my question about where they are)
=> Added the Lyra addresses

src/.vuepress/config.js, src/.vuepress/styles/index.styl
Various minor tweaks that make the website a lot prettier (at least in my opinion). Feel free to give your own opinion.
=> feat: make the website prettier

src/.vuepress/config.js, src/docs/developers/known-issues.md
Adds a "known issues" page for the purpose of distributing information about known bugs. Adds an entry to that page for the gas pricing discrepancy that we found w/r/t warm and cold storage slots.
**Metadata**
- Fixes INT-366
=> feat: add known issues page

src/docs/developers/l2/new-fees.md
Reference fee code did not call ethers correctly.
=> Fixed reference for fee docs, ethers interaction

src/docs/developers/l2/dev-node.md, src/docs/infra/networks.md
Updated to new networks page + added notes about not using our RPC endpoint in prod.
=> Updated networks page

src/.vuepress/enhanceApp.js, src/README.md, src/docs/README.md
Updated the home page to a more approachable breakdown of available content.
=> Updated home page

README.md, src/.vuepress/components/Home.vue, src/.vuepress/config.js, src/README.md, src/docs/developers/bridge/messaging.md, src/docs/developers/bridge/standard-bridge.md, src/docs/developers/known-issues.md, src/docs/developers/l2/contracts-2.0.md, src/docs/developers/l2/dev-node.md, src/docs/developers/l2/differences.md, src/docs/developers/l2/json-rpc.md, src/docs/developers/l2/new-fees.md, src/docs/developers/tutorials.md, src/docs/developers/util.md, src/docs/infra/networks.md, src/docs/protocol/challenges.md, src/docs/protocol/protocol-2.0.md, src/docs/protocol/sequencing.md, src/docs/users/deposit.md, src/docs/users/fees-2.0.md, src/docs/users/getting-started.md, src/docs/users/metamask.md, src/docs/users/withdrawal.md
Rename OE to Optimism since we're going for this rebrand.
=> fix: oe => optimism

src/.vuepress/styles/index.styl
Just some minor styling updates. Main change is to remove the underlines from things that aren't links (per suggestion from @lanceplaine).
=> fix: minor styling updates

src/docs/infra/networks.md
[Requested by @K-Ho](https://optimism-workspace.slack.com/archives/C01TQ2ZEPAN/p1640249248092100)
=> Changed the warning as requested on Slack

src/docs/infra/networks.md
Fix broken link to the "Get in Touch" typeform.
=> Fix broken link to the "Get in touch" typeform

src/docs/developers/l2/new-fees.md
This PR fixes multiple bugs in the L1 fee example found by a discord user.
=> fix: bugs in L1 fee example

src/docs/developers/README.md
Adds an intro page for the Dev Docs section
=> feat: add dev docs intro

src/.vuepress/theme/components/Anchor.js, src/.vuepress/theme/components/PageMeta.vue
Updates the style of the footer to match the design by @lanceplaine.
=> feat: update footer style

src/docs/developers/build/differences.md, src/docs/developers/build/transaction-fees.md
Updates for the reduction of fees and new timestamp logic
=> Updates for recent settings changes

src/docs/developers/l2/new-fees.md
Early release of the transaction fees content from the new documentation release #313 as this specific content is causing confusion. This also includes the new fixed and dynamic overhead costs which were lowered earlier this week. 
**Metadata**
- Fixes INT-471
=> Transaction fees page rewrite

src/.vuepress/config.js, src/docs/protocol/README.md
Updates protocol specs page to add brief explanation of current state and links to specs repo and cannon.
=> Update protocol specs holding page

src/docs/how-optimism-works/README.md
Tiny tweaks to How Optimism Works, also breaking paragraphs out into different lines for easier editing in the future.
=> fix: final how tweaks

src/docs/guides/README.md, src/docs/guides/wallet-dev.md
Cleans up the wallet guide and cuts it down to the most important information.
=> feat: clean up wallet guide

src/docs/developers/build/differences.md
=> Added an explanation of why address aliasing is important

src/docs/developers/build/differences.md
=> feat(docs): Added the timestamp frequency

src/docs/developers/tutorials.md
Adds link for dapptools in tutorials
**Metadata**
- Fixes #366
=> feat(docs/developers): add link for dapptools in tutorials

src/docs/developers/build/json-rpc.md
As requested by @optimisticben
=> fix(json-rpc): Remove the deprecation notices

src/.vuepress/config.js, src/docs/guides/testing.md
Five tokens, four pools
Closing: INT-552
=> feat(testing): Added the initial testing docs

src/docs/useful-tools/faucets.md
=> Added optifaucet.com

src/.vuepress/config.js, src/docs/useful-tools/oracles.md
Missing Band Protocol because I couldn't find the relevant information
Missing oracle types
Closing: #359
Closing: INT-544
=> feat(tools): Oracles page

src/docs/developers/tutorials.md
=> fix(tutorials): Updated to what we have now

src/docs/useful-tools/explorers.md
Directions from @smartcontracts  (a.k.a. Kelvin)
=> feat(explorer): Add pre (June 23rd) history

src/docs/developers/bridge/messaging.md, src/docs/developers/bridge/standard-bridge.md, src/docs/developers/build/transaction-fees.md
Closing: INT-578, INT-579, INT-580, INT-581
=> Replace code in docs with links to tutorials

src/.vuepress/config.js, src/docs/developers/build/testing-dapps.md
As requested by @smartcontracts at https://discord.com/channels/667044843901681675/887914409207414785/960605200371048529
Closing: INT-573
=> feat(testing-dapps): Testing best practices

src/docs/protocol/sequencing.md
=> fix(protocol/sequencing): Added a redirect since search engines still expect it

src/docs/developers/build/run-a-node.md
Based on user input that @snario got.
https://optimism-workspace.slack.com/archives/C03BK47JV6J/p1650789083306749
=> fix(run-a-node): Monorepository to monorepo

src/docs/useful-tools/providers.md
The same entry for Infura was two times in the list. I removed the 2nd one which missed the Description and pricing header
=> remove duplicated infura entry

src/docs/governance/gov-fund.md
=> fix(gov-fund): banner, add C

.github/CODEOWNERS
@Nicca42 , we need a backup person to approve PRs during your vacation. Can you please merge this?
=> feat(CODEOWNERS): Add backup

src/.vuepress/config.js, src/docs/governance/gov-01.md
As requested by Bobby (https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1652828078537819).
Closing: INT-599
=> feat(gov-0.1): first version

src/docs/governance/README.md
As requested in https://optimism-workspace.slack.com/archives/C02NSQ6SR5X/p1652370227622799
=> feat(governance): Added that they can help by using the governance forum

src/docs/useful-tools/networks.md, src/docs/useful-tools/providers.md
We have added Optimism Mainnet dedicated API support and Public API support on :
https://blastapi.io/
https://blastapi.io/public-api
We also wanted these features to be reflected in the documentation, so developers can use them right away:
https://twitter.com/optimismPBC/status/1529175842185682951
=> Add BlastApi on Optimism documentation

src/docs/developers/build/using-tools.md
Mention [Waffle](https://github.com/TrueFiEng/Waffle) testing framework in `Using your favorite tools` section.
=> Add Waffle docs

src/docs/developers/build/dev-node.md
There's enough left there for people to make a development node, and I don't want to spend more time on it this close to bedrock.
Bedrock will be close to a full rewrite.
Closing: INT-601
=> fix(devnode): Removed some options that didn't work

src/docs/useful-tools/faucets.md
As requested [here](https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1656344038312829).
=> fix(faucets): Added text requested by Zain

src/docs/protocol/protocol-2.0.md
Fix a typo on predeployed contracts section
=> docs: fix typo

src/docs/useful-tools/networks.md
As per https://optimism-workspace.slack.com/archives/C02MWK11M27/p1656613014277439?thread_ts=1656578616.677859&cid=C02MWK11M27
=> feat(networks): Added the limitation on web socket endpoints

src/docs/useful-tools/providers.md
Added Pocket Network to the list of Node Providers for Optimism
Pocket Network is a decentralized, multi-chain RPC protocol.
=> Update providers.md with Pocket Network

src/.vuepress/config.js, src/docs/developers/bedrock.md, src/docs/governance/airdrop-1.md
As requested in https://optimism-workspace.slack.com/archives/C024PBT72ET/p1657658315314349?thread_ts=1657644646.113239&cid=C024PBT72ET
=> feat(several): On Twitter OptimismPBC -> OptimismFND

src/docs/developers/build/testing-dapps.md, src/docs/guides/smart-contract-devs.md, src/docs/guides/testing.md, src/docs/useful-tools/networks.md
=> feat(networks): Add Goerli testnet

src/.vuepress/config.js, src/docs/developers/bridge/comm-strategies.md, src/docs/developers/bridge/messaging.md
Replacing: #388
Closing: INT-582
=> feat(interlayer comm strategies).

src/docs/developers/README.md, src/docs/developers/build/basic-contract.md, src/docs/developers/build/run-a-node.md, src/docs/developers/build/using-tools.md, src/docs/developers/releases.md, src/docs/guides/cex-dev.md, src/docs/guides/testing.md, src/docs/guides/wallet-dev.md, src/docs/useful-tools/debugging.md, src/docs/useful-tools/explorers.md, src/docs/useful-tools/faucets.md, src/docs/useful-tools/monitoring.md, src/docs/useful-tools/networks.md, src/docs/useful-tools/oracles.md, src/docs/useful-tools/providers.md
Closing: ENG-2449, DOCS-622, ENG-2484
=> Update more docs to have Goerli

src/docs/developers/bridge/messaging.md
better explanation of the wait period for L2->L1
Closing: DOCS-626
=> fix(messaging): Kovan -> Goerli

src/docs/governance/allocations.md
Allocations can now be requested on the governance forum.
=> Remove outdated "May 3" reference

src/docs/how-optimism-works/README.md
Spelling correction Line 52: cotinously -> continuously
=> Spelling correction

src/docs/developers/bridge/standard-bridge.md
=> Update standard bridge file typo

src/docs/developers/bedrock.md
As requested by @K-Ho , https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1659372766275029
=> feat(bedrock): Remove smoothing, since it's been postponed

src/docs/useful-tools/networks.md, src/docs/useful-tools/providers.md
1. Add GetBlock because it works now (verified)
2. Turned all lists of providers in networks.md into links to providers.md because the list is getting large and dynamic.
=> Node providers updates:

src/.vuepress/config.js, src/docs/developers/build/cheap-dapp.md
=> feat(cheap-dapp): Initial version

src/docs/developers/bedrock.md
Based on [the AMA from August 8th](https://twitter.com/optimismFND/status/1556678892160557056).
Closing: ENG-2568
=> feat(bedrock): Add information from the AMA

src/docs/guides/testing.md
=> feat(testing): Added OUT tokens for Optimism Goerli

src/docs/useful-tools/networks.md
It's now Oct 5th (see https://optimism-workspace.slack.com/archives/C024PBT72ET/p1660310876477049).
=> Changed the date of Kovan end of life

src/docs/guides/testing.md
=> feat(testing): Added ERC-721 faucet

src/docs/useful-tools/providers.md
=> Modify the providers page as requested by Alchemy

src/docs/developers/build/using-tools.md
Correct a typo in the docs for the hardhat configuration of optimism on goerli
https://community.optimism.io/docs/developers/build/using-tools/#hardhat
**Metadata**
n/a
=> correct typo, georli -> goerli

src/docs/guides/testing.md
As per https://optimism-workspace.slack.com/archives/C02KCKY69ST/p1663081580819339?thread_ts=1663081290.077089&cid=C02KCKY69ST
=> feat(testing): Add WETH

src/docs/guides/wallet-dev.md
Clarified language + mentioned Alchemy as the recommended provider
=> Updated the getting up and running node options

src/docs/guides/cex-dev.md
Given ever decreasing throughput limits, wanted to emphasize the importance of a private rpc provider and that Alchemy was the preferred provider. Pls lmk if you have any questions, thank you :)
=> Emphasize the use of a private rpc provider

src/docs/developers/bridge/standard-bridge.md
=> Warning about unbridgeable tokens

src/docs/guides/testing.md, src/docs/useful-tools/debugging.md, src/docs/useful-tools/explorers.md, src/docs/useful-tools/monitoring.md, src/docs/useful-tools/networks.md, src/docs/useful-tools/oracles.md
=> feat(*): Update testnet explorer to Etherscan

src/docs/developers/build/testing-dapps.md, src/docs/guides/cex-dev.md, src/docs/guides/wallet-dev.md, src/docs/useful-tools/networks.md
So it won't extend to half the page
=> fix(network): Fix the warning

src/.vuepress/config.js, src/docs/sdk/alchemy-sdk.md, src/docs/sdk/js-client.md
=> Links to Alchemy SDK as they requested

src/.vuepress/config.js, src/docs/useful-tools/oracles.md
=> Add Portal's Randomness oracle

src/docs/developers/tutorials.md, src/docs/sdk/alchemy-sdk.md
Also, fix tutorials.md to point to up to date bridge tutorials
=> feat(*): Add affiliate info to Alchemy deep links

src/.vuepress/config.js, src/docs/developers/media.md
Mostly ETHOnline summit, Sept. 22nd, 2022
Closing: DOCS-665
=> feat(media): Initial version

src/.vuepress/config.js, src/.vuepress/theme/components/Navbar/Navbar.vue, src/.vuepress/theme/components/Navbar/SidebarButton.vue, src/.vuepress/theme/components/Sidebar/Sidebar.vue, src/.vuepress/theme/components/Sidebar/SidebarNavLinks.vue, src/.vuepress/theme/styles/palette.styl, src/README.md, src/docs/how-optimism-works/README.md, src/docs/security-model/README.md
Adds a security model page. Part of our efforts to increase transparency globally.
=> feat: add security model page

src/.vuepress/config.js, src/docs/protocol/README.md, src/docs/security-model/README.md, src/docs/security-model/bounties.md, src/docs/security-model/optimism-security-model.md
Cleaning up + adding more info
=> Security page clean up

src/.vuepress/config.js
=> Shortened top level page names

src/docs/useful-tools/networks.md, src/docs/useful-tools/providers.md
=> fix(networks, providers): Per Alchemy requests

src/docs/developers/build/transaction-fees.md
=> feat(tx-fees): Add how to get parameter values

src/docs/governance/README.md
As requested by Tasia at https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1665518675299749
=> fix(governance README.md): Anything -> Everything

src/docs/how-optimism-works/README.md, src/docs/protocol/2-rollup-protocol.md
=> feat(how-to): Changed owner from PBC to Foundation

src/docs/governance/airdrop-1.md
Remove dashboard link since it's not from/endorsed by the Collective.
- Added a dashboard from the Optimism team account in references: https://dune.com/optimismfnd/optimism-airdrop-1
**Tests**
**Metadata**
=> Update Airdrop #1 Dashboard in Docs

src/docs/developers/bedrock-temp/infra.md, src/docs/developers/bedrock.md
=> feat(bedrock): Update expected date to Q1 2023

src/docs/developers/bridge/standard-bridge.md, src/docs/developers/build/differences.md, src/docs/developers/build/run-a-node.md, src/docs/developers/build/transaction-fees.md, src/docs/governance/README.md, src/docs/governance/airdrop-1.md, src/docs/guides/cex-dev.md, src/docs/guides/testing.md, src/docs/how-optimism-works/README.md, src/docs/protocol/2-rollup-protocol.md, src/docs/protocol/compressed-ctc.md, src/docs/useful-tools/networks.md, src/docs/useful-tools/oracles.md
As requested by Tasia
Closing: DOCS-691
=> feat(*): Change the explorer link to explorer.optimism.io

src/docs/developers/bridge/standard-bridge.md, src/docs/guides/bridge-dev.md, src/docs/guides/cex-dev.md, src/docs/sdk/js-client.md
As reqeusted: https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1666706824094299
=> fix(*): Link to bridge tutorial

src/docs/developers/build/differences.md
=> feat(differences): Update for bedrock

src/docs/guides/wallet-dev.md
=> feat(wallet-dev): Add ref to `rollup_gasPrices`

src/docs/developers/build/differences.md
As requested in https://optimism-workspace.slack.com/archives/C024PBT72ET/p1665941231601959
=> feat(differences): Add we no longer support EIP-155

src/docs/developers/build/differences.md
Based on https://optimism-workspace.slack.com/archives/C03BK47JV6J/p1667403903017679?thread_ts=1667361912.286359&cid=C03BK47JV6J
=> feat(differences): Link from DIFFICULTY to a real randomness source

src/.vuepress/config.js
Updates the algolia search key. Algolia no longer maintains the old index.
=> fix: new algolia key

src/docs/governance/README.md
=> fix(governance): RetroPFG -> RetroPGF

src/docs/developers/build/run-a-node.md
=> feat(run-a-node): How to choose whether to sync from L1 or L2

src/docs/useful-tools/networks.md
Needed based on https://discord.com/channels/667044843901681675/887914409207414785/1039810586873188382
=> feat(networks): Added explanation of non-user networks

src/.vuepress/theme/components/Page.vue
=> feat(*): Add Google Analytics

src/docs/developers/bedrock-temp/node-operator-guide.md
Adds some sections on troubleshooting common node operation issues. These were issues encountered by infra providers during the migration rehearsal.
=> Add Bedrock troubleshooting

src/.vuepress/config.js, src/README.md
Based on https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1671292863267219?thread_ts=1671286522.556719&cid=C0214EMUUJ3
=> fix(front-page): Fix the How Optimism Works tile

src/.vuepress/config.js, src/docs/biz/README.md
Replacing PR #543
Copying https://help.optimism.io/hc/en-us/articles/9762044018843-How-do-I-get-project-support-marketing-integrations-etc-
=> feat(biz): Add project support

src/docs/governance/proposals.md
Updating temporarily to let proposers know the process is changing due to the election of a Grants Council 
Another update will follow once the Grants Council has published a new grant proposal process
=> Update Proposer Section for Grants Council

src/.vuepress/config.js, src/docs/developers/bedrock/bedrock.md
This new PR should be something @Nicca42  can approve and merge.
=> Added homepage back (replacing #575)

src/docs/useful-tools/providers.md
Add Nodereal as Optimism provider. 
**Tests**
**Invariants**
For changes to critical code paths, please list and describe the invariants or key security properties of your new or changed code.
**Metadata**
=> Add NodeReal as infra provider

src/docs/developers/bedrock/bedrock.md, src/docs/developers/bedrock/node-operator-guide.md
Based on https://oplabs-pbc.slack.com/archives/CQZ0U9FAN/p1672896164633669
=> feat(bedrock): Add link to forkdiff

src/docs/governance/attestation-station.md
Adding Clique's attestation product (comms go out this wk)
=> Adding Clique's attestation product

src/docs/developers/bedrock/node-operator-guide.md
As requested in https://oplabs-pbc.slack.com/archives/C01R0SBFYHJ/p1672846257789509
=> fix(node-operator-guide): l2geth purpose clarified

src/docs/useful-tools/oracles.md
As requested in https://oplabs-pbc.slack.com/archives/C0214EMUUJ3/p1673012870473229
=> feat(oracles): Add the Band VRF

src/docs/developers/build/differences.md, src/docs/governance/attestation-station.md, src/docs/useful-tools/debugging.md, src/docs/useful-tools/explorers.md, src/docs/useful-tools/monitoring.md
As requested in https://oplabs-pbc.slack.com/archives/C037YKXU971/p1673051596640399 by liam.
=> feat(*): optimistic.etherscan.io -> explorer.optimism.io

src/docs/developers/bedrock/public-testnets.md
=> Add op-node images

src/docs/governance/retropgf-2.md
- Updated links to nominations
- language changes based on recent changes
- Updated timelines
- Link to Project Manual
=> Update RetroPGF doc

src/docs/contribute/README.md
=> Adding link to project ideas

src/docs/governance/retropgf-2.md
Timelines updated to 
Project opt-in deadline: Feb 14
Voting window: Feb 28 - Mar 14
=> Updated timelines RPGF2

src/.vuepress/config.js, src/docs/useful-tools/meta-tx.md
=> feat(meta-tx): First version

src/docs/developers/bedrock/public-testnets.md
=> Add Block Explorer URL to Goerli details

src/docs/governance/existing-delegate.md, src/docs/governance/proposals.md
=> feat(governance): Add "this is changing banners"

src/docs/developers/bridge/messaging.md
Closing: https://linear.app/optimism/issue/DOCS-733/update-docs-for-bedrock-withdrawals
=> feat(messaging): Add the proving stage 

src/.vuepress/config.js
As requested in https://discord.com/channels/667044843901681675/950505547440996442/1070244988434260011
=> fix(toc): Link to GovFund tracker

src/.vuepress/config.js, src/docs/developers/bedrock/README.md
As per https://oplabs-pbc.slack.com/archives/C0214EMUUJ3/p1675355519365249
=> fix(bedrock): Hopefully fix docs/developers/bedrock/#

src/.vuepress/theme/components/Anchor.js, src/.vuepress/theme/components/PageMeta.vue
We have a couple of links inside the Theme that haven't been updated yet.
=> feat(Anchor): Update typeform to new domain

src/docs/governance/retropgf-2.md
- Add link to RetroPGF application manager
- Change tenses
=> Update Opt-in step

src/docs/governance/allocations.md
+ added sentence to stop spamming forum for airdrops
=> Updated to link to grants council

src/docs/governance/proposals.md
New process for grants proposals
=> updated to reflect grants council process

src/docs/governance/gov-fund.md
Update to reflect grants council and gov fund charter
=> Update for grants council

src/docs/governance/existing-delegate.md
Updated for grants council and agora voting platform
=> Update for grants council and agora voting

src/docs/security-model/bounties.md, src/docs/security-model/optimism-security-model.md
1. Add link about our Sherlock audit contest for Bedrock.
2. Fix broken links.
=> Security Model page: adding Sherlock and fixing broken link.

src/docs/governance/token-house-history.md
Adds Reflection Period #2 
Updates history for S2
Adds info for S3
=> Update to reflect RP2 and S3

src/docs/governance/howto-delegate.md
=> update process for agora

src/docs/guides/bridge-dev.md, src/docs/guides/wallet-dev.md, src/docs/protocol/1-design-philosophy.md, src/docs/protocol/compressed-ctc.md, src/docs/protocol/protocol-2.0.md, src/docs/sdk/README.md, src/docs/security-model/README.md, src/docs/useful-tools/debugging.md, src/docs/useful-tools/meta-tx.md, src/docs/useful-tools/networks.md, src/docs/useful-tools/oracles.md, src/docs/useful-tools/providers.md
=> Fix: typos

src/docs/governance/delegate.md
Add "Optimism Agora" after Optimism Governance Portal (maybe people are not familiar with this name) and update the other parts a bit.
Path : src/docs/governance/delegate.md
**Tests**
-
**Invariants**
-
-
**Metadata**
-
=> Add more detail in page

src/docs/governance/retropgf-2.md
Voting window has been changed from 28th of Feb -  14th of March to 7th of March - 21st of March
=> Update RetroPGF2 timelines

src/docs/useful-tools/faucets.md
=> Add CB Faucet

src/docs/governance/attestation-station.md
Adding ref to Clique Zk attestations
=> Adding Clique ZK attestations

src/.vuepress/config.js, src/docs/governance/allocations.md, src/docs/governance/what-is-the-optimism-foundation.md
**Tests**
**Invariants**
For changes to critical code paths, please list and describe the invariants or key security properties of your new or changed code.
**Metadata**
=> feat(allocations, what-is-the-optimism-foundation): Bobby requested changes.

src/docs/useful-tools/providers.md
Updated the description of Infura's Optimism node service and added more information around pricing and sign-ups.
=> Updated Infura description in node provider directory

src/docs/developers/bedrock/differences.md
=> feat(bedrock differences): The two message passer contracts

src/docs/developers/bedrock/differences.md, src/docs/developers/known-issues.md
So far there is one - the lack of a chainID in deposit txns
Closing: CLI-3444
=> feat(known-issues): Added known non-issues

src/docs/developers/bridge/standard-bridge.md
- [Fee on Transfer tokens](https://github.com/d-xo/weird-erc20#fee-on-transfer)
- [Tokens that modify balances without emitting a Transfer event](https://github.com/d-xo/weird-erc20#balance-modifications-outside-of-transfers-rebasingairdrops)
As requested at https://oplabs-pbc.slack.com/archives/C0229H2N4MD/p1677793120544359
=> feat(standard-bridge): Add warning about weird ERC-20

src/docs/guides/nft.md
Added a minor change to the file by including QuickNode NFT API
=> Update nft.md with QuickNode NFT API

src/docs/developers/build/differences.md
Hi OP crew - I believe this is a typo?
=> msg.origin typo

src/docs/governance/attestation-station.md
=> Add RociFi

src/.vuepress/config.js
Retry of https://github.com/ethereum-optimism/community-hub/pull/686
=> Retry of 686

src/docs/protocol/2-rollup-protocol.md
Replacing #687 which got synk errors I cannot view.
=> feat(2-rollup-protocol): Change CTC addr (and change bedrock to Q2)

src/docs/biz/README.md, src/docs/developers/bedrock/node-operator-guide.md, src/docs/developers/bedrock/public-testnets.md, src/docs/developers/bedrock/upgrade-guide.md, src/docs/developers/media.md
=> feat(*): Make the PBC vs. Foundation distinction clearer

src/.vuepress/config.js, src/docs/developers/media.md, src/docs/governance/media.md
Also, split dev and gov videos.
Closing: DEVRL-800
=> feat(media): Add ETHDenver videos

src/docs/developers/known-issues.md
I am correcting a typo
**Tests**
N/A
**Invariants**
N/A
**Metadata**
**TODOs**
=> Correct typo in sentence about known issues

src/.vuepress/config.js, src/docs/contribute/Ambassador-req.md
Added the ambassador program requirements to the docs.
=> Ambassador requirements

src/docs/developers/bedrock/upgrade-guide.md
Fixes dates laid out in the "upgrade guide" for Bedrock
=> Fix bedrock date

src/docs/governance/attestation-station.md
Otterspace launched their Otterspace Score on ATST, including link
=> Include Otterspace Score

src/docs/developers/bridge/standard-bridge.md
The previous example is actually a pattern we want to avoid with updating the tokenlist. The example this PR provides is the proper way that a new token should be added.
=> Update the example for updating the tokenlist to a better example

src/docs/developers/bedrock/public-testnets.md
Fixes an issue that would cause the build to break because window was not defined on the server side.
=> fix: broken build

src/docs/governance/airdrop-1.md, src/docs/guides/wallet-dev.md, src/docs/protocol/2-rollup-protocol.md, src/docs/sdk/README.md, src/docs/useful-tools/meta-tx.md, src/docs/useful-tools/oracles.md
=> fix(*): on chain -> onchain, off chain -> offchain

src/.vuepress/config.js, src/docs/security-model/priv-roles.md
Closing: DEVRL-796
Based on @maurelian 's doc
=> feat(security/priv-roles): First version

src/.vuepress/config.js
Fixes some small build warnings related to sidebar config. Makes the site slightly cleaner.
=> fix: update sidebar config

src/docs/developers/bedrock/differences.md, src/docs/developers/bedrock/explainer.md, src/docs/developers/build/testing-dapps.md, src/docs/guides/cex-dev.md, src/docs/useful-tools/faucets.md, src/docs/useful-tools/networks.md, src/docs/useful-tools/oracles.md
Fixed some broken links in the docs and removed obsolete ones. Also added helpful resources where applicable.
=> Fix broken links and remove obselete ones

src/docs/governance/media.md
=> fix(governance/media): Correct DAO archive link

src/docs/identity/README.md, src/docs/identity/build.md, src/docs/identity/glossary.md
Adding language around multiplayer db
=> Multiplayer copy changes

src/docs/identity/README.md, src/docs/identity/atst-v0.md, src/docs/identity/atst-v1.md, src/docs/identity/build.md, src/docs/identity/glossary.md
=> Copy cleanup

src/.vuepress/theme/components/Page.vue
As requested in: https://oplabs-pbc.slack.com/archives/C0214EMUUJ3/p1684500166445149
=> fix(banner): Make it work with the breadcrumbs

src/docs/useful-tools/providers.md
Adding OnFinality services description and RPC Endpoint for Optimism.
=> Add OnFinality RPC Endpoint for Optimism

src/docs/useful-tools/providers.md
Added BlockSpaces as public RPC endpoint provider
**Tests**
no tests, only txt. link added.
**Invariants**
For changes to critical code paths, please list and describe the invariants or key security properties of your new or changed code.
**Metadata**
=> Added BlockSpaces as public RPC endpoint provider

src/docs/developers/bedrock/differences.md
=> feat(differences): Put finalized EIP-1559 values

src/docs/developers/build/transaction-fees.md
=> feat(tx-fees): Update for bedrock's EIP 1559

package.json, yarn.lock
- Add a preview mode
- Yarn preview will run the docs in production mode
- This allows folks to preview the docs as they run in prod
=> feat: Add preview mode

src/.vuepress/theme/components/Home.vue, src/.vuepress/theme/components/Page.vue
=> feat(banner): Updated from future to present

src/docs/developers/build/cheap-dapp.md, src/docs/developers/build/transaction-fees.md, src/docs/useful-tools/monitoring.md
=> feat(*): Change grafana dashboard to Dune dashboard

src/docs/useful-tools/networks.md
Adds file sizes to datadir and a footnote to clarify how to uncompress the zstd file.
=> Add datadir file sizes and zstd note

src/docs/developers/bedrock/differences.md
=> fix(differences): Wrong elasticity multiplier

src/docs/developers/build/run-a-node.md, src/docs/useful-tools/networks.md
=> feat(networks and run-a-node): Update to latest storage

src/docs/governance/get-a-grant.md
Update the links for the grants council to their s4 docs.
=> updated grant links

src/.vuepress/config.js
Update config to include RetroPGF 1 page under citizens hous
=> Update config.js to include RetroPGF 1 page

src/.vuepress/config.js
=> Add RetroPGF3 to config

src/docs/governance/get-a-grant.md
Took out sentence about grant size
=> Update partner fund language.md

src/docs/governance/get-a-grant.md
Was linking to RFP repo not Partner Fund application form
=> Update partner fund link.md

src/docs/developers/bedrock/differences.md
As requested **and approved** by @zain
Closing: DEVRL-1008
=> feat(differences): Specify deposits are about 1 minute

src/docs/guides/nft.md
=> Add NFTScan and Resevoir to indexing

src/docs/developers/bedrock/wallet-upgrade.md, src/docs/guides/wallet-dev.md
=> feat(wallet-dev, wallet-upgrade): Explain base fee better

src/docs/useful-tools/networks.md
=> feat(networks): Add cryptographic checksums

src/docs/developers/build/run-a-node.md
Also:
- Fix the title typo
- Add a script to check how long until synchronization is complete
Closing: DEVRL-1021
=> feat(run-a-node): Speed up initial sync with p2p

src/docs/useful-tools/explorers.md
As requested by Stefan Ignjatovic from Tenderly (on Slack)
Closing: DEVRL-1017
=> feat(explorers): Add Tenderly

src/docs/useful-tools/monitoring.md
As requested by Stefan Ignjatovic from Tenderly (on Slack)
Closing: DEVRL-1016
=> feat(monitoring): Add Tenderly

src/docs/useful-tools/networks.md
We no longer publish the addresses on private network
Closing: DEVRL-1003
=> feat(networks): Remove out of date warning

src/docs/developers/build/differences.md
Closing: DEVRL-992
Requested as an FAQ
=> feat(build/differences): Add the fact we don't support PUSH0 yet

src/docs/protocol/2-rollup-protocol.md
=> Fix block storage address for mainnet

src/docs/developers/bridge/comm-strategies.md
=> feat(comm-strategies): Update for bedrock (add the proving txn)

src/docs/protocol/protocol-2.0.md
=> feat(protocol/protocol-2.0): Update contract descriptions to Bedrock

src/docs/governance/retropgf-3.md
fixing typos and grammar, i.e. `allocat --> allocate`
=> fix: typo and correct grammar.md

src/docs/useful-tools/debugging.md
As requested by Stefan Ignjatovic from Tenderly (on Slack)
Closing: DEVRL-1015
=> feat(debugging): Change the Tenderly description

src/docs/governance/airdrop-1.md
=> feat(airdrop-1): Add the airdrop is still available until July 1st, 2024

src/docs/useful-tools/faucets.md
Staging copy change for Superchain Faucet.
=> Update Faucet to mention Superchain Faucet

src/docs/developers/build/differences.md
Close: [DEVRL-1065](https://linear.app/optimism/issue/DEVRL-1065)
=> feat(differences): Add the mempool

src/docs/developers/build/json-rpc.md
`'--data` - that was quoted but `--data` dont need that.
=> Fix typo and adjust formatting to similar style.

src/.vuepress/config.js, src/docs/governance/law-of-chains-disclaimer.md
Adding law of chains disclaimer to the docs
=> adding law of chains disclaimer

src/docs/governance/law-of-chains-disclaimer.md
=> updating disclaimer

src/docs/governance/law-of-chains-disclaimer.md
=> fixing typo

src/.vuepress/config.js
Missed in previous PR, missed in #869
=> Update config to include AA

src/docs/useful-tools/faucets.md
- Fix naming convention
- Fix formatting
- Fix URLs
- Add guide for bridging from L1
=> Updating copy on faucets

src/docs/guides/README.md
Adding faucet information to our quick start page.
**Tests**
n/a
**Metadata**
- Fixes https://github.com/ethereum-optimism/developer-support/issues/52
=> adding faucet info to quick start

src/.vuepress/config.js, src/docs/contribute/contribution-path/techNERDs.md, src/docs/developers/bedrock/differences.md, src/docs/developers/bedrock/wallet-upgrade.md, src/docs/developers/build/dev-node.md, src/docs/developers/build/run-a-node.md, src/docs/developers/build/transaction-fees.md, src/docs/guides/cex-dev.md, src/docs/guides/wallet-dev.md, src/docs/protocol/txn-flow.md, src/docs/useful-tools/README.md, src/docs/useful-tools/faucets.md, src/docs/useful-tools/monitoring.md, src/docs/useful-tools/networks.md, src/docs/useful-tools/providers.md
Updates to rpc provider information
**Tests**
n/a
**Metadata**
- closes: https://github.com/ethereum-optimism/developer-support/issues/81
=> Rpc provider updates

src/docs/governance/airdrop-1.md
Updated link to airdrop 1 csv list
=> updated airdrop 1 csv link

src/docs/developers/bedrock/node-operator-guide.md
Hey :wave:,
This PR will fix :
1 typo in `src/docs/developers/bedrock/node-operator-guide.md`
Best!
=> docs: fix typos

src/docs/developers/bedrock/node-operator-guide.md, src/docs/developers/build/run-a-node.md, src/docs/useful-tools/networks.md
Update docs to include initial sepolia info + how to run a sepolia node
=> Add Sepolia dev docs

src/docs/developers/bridge/messaging.md
Adding the testnet withdraw challenge period.
**Tests**
n/a
This will be added to the bridge UI for testnet withdrawals
**Metadata**
- Fixes https://github.com/ethereum-optimism/developer-support/issues/80
=> Adding testnet withdraw challenge period time

src/docs/developers/build/run-a-node.md, src/docs/security-model/README.md
We don't maintain the simple-optimism-node repo so I'm removing references to it.
**Tests**
n/a
n/a
**Metadata**
- resolves https://github.com/ethereum-optimism/developer-support/issues/117
=> removing references

src/docs/contribute/important-terms.md
=> Superchain term update

src/docs/useful-tools/explorers.md
Adding Blockscout's OP Sepolia link
**Tests**
n/a
**Metadata**
=> adding blockscout's op sepolia link

src/docs/useful-tools/networks.md
Adding explorer link to the networks page.
**Tests**
n/a
**Metadata**
- Fixes https://github.com/ethereum-optimism/developer-support/issues/145
=> adding op sepolia explorer link

src/docs/identity/atst-v0.md
=> Fix broken link in atst-v0.md

src/.vuepress/config.js, src/docs/identity/profile.md, src/docs/identity/schemas.md
Adding schemas for RPGF, Lists, etc.
=> Add page for schemas

src/docs/biz/README.md
- Updating out of date links
- Removed form that is no longer supported
**Tests**
n/a
**Metadata**
=> updating out of date links

src/docs/governance/airdrop-1.md
=> update airdrop-1.md docs

src/docs/security-model/README.md
The link to our security audits was not pointing to the right place
**Tests**
**Metadata**
=> Updating broken link

src/docs/governance/airdrop-3.md
Updating the address list link
**Tests**
**Metadata**
=> fixing the address list link

src/docs/governance/airdrop-3.md
Adding clarity around how airdrop 3 works.
**Tests**
**Metadata**
=> clarifying how it works

src/docs/identity/profile.md
Add QA for multiple applications
=> Add QA for multiple applications

.github/ISSUE_TEMPLATE/issues.md
=> Update issues.md - Fix Discord Link

src/docs/identity/build.md
Broken link, updating to https://optimism.easscan.org/
=> Fixing EAS links

src/docs/governance/get-a-grant.md
Updated Collective Intents link
Flagged by BD team, link was double linked with an old forum post, so it went to an error page
=> Update Collective Intents link get-a-grant.md

src/.vuepress/theme/components/Anchor.js
New contact form link: https://airtable.com/appQ2S9IatldkoNQw/pagyJSUyxJA2SQKO3/form
=> Fix deadlink support form

src/docs/contribute/demo-day.md
updated demo day doc to reflect current demo day process
=> demo doc updated

src/docs/governance/airdrop-4.md
=> Fix attribute criteria name

src/docs/governance/README.md, src/docs/governance/allocations.md, src/docs/governance/citizens-house.md, src/docs/governance/citizenship.md, src/docs/governance/get-a-grant.md, src/docs/governance/retropgf-1.md, src/docs/governance/retropgf-2.md, src/docs/governance/retropgf-3.md
Closes #1011 
Closes #1012 
Closes #1013 
Closes #1014 
Closes #1015 
Closes #1016 
Closes #1017 
Closes #1018
=> Opmxwell mega branch

.github/CODEOWNERS
=> Update CODEOWNERS to add Julien

public/service-worker.js
=> fix: force service worker to clear cache

pages/op-token/airdrops/_meta.json, pages/op-token/airdrops/airdrop-5.mdx, pnpm-lock.yaml, theme.config.tsx, words.txt
=> airdrop 5 page

package-lock.json, pages/welcome/faq/_meta.json, pages/welcome/faq/relevant-dashboards-trackers-addresses.mdx, pnpm-lock.yaml
Adding in a new page with relevant information about trackers, dashboards, and addresses
=> Adding in new page for dashboard, trackers, and addresses

pages/_meta.json, pages/research/_meta.json, pages/research/research-overview.mdx, words.txt
Adding in new page for Research and Experimentation at Optimism
=> New Research Page

pages/grant/grant-overview.mdx
Reverts ethereum-optimism/community-hub#1090
=> Revert "Update grant-overview.mdx"

pages/citizens-house/rounds/_meta.json, pages/citizens-house/rounds/retropgf-5.mdx, pages/citizens-house/rounds/retropgf-6.mdx
I don't have write access, so I had to fork and create a new PR based on #1102
=> Opmxwell patch 9

pages/citizens-house/rounds/retropgf-5.mdx, pages/citizens-house/rounds/retropgf-6.mdx
PR to add Retro Round 5 + 6 info to the gov docs
=> PR to add Retro Round 5 + 6 info

styles/global.css, theme.config.tsx
Adds a new footer, similar to the one on the dev docs
=> Adds a new footer

pages/identity/schemas.mdx
=> Update schemas to add refUID field to citizen schema.mdx

pages/op-token/superstacks-allocation.mdx
=> update the link to claim

pages/contribute/contribution-path/technerds.mdx
Updated the techNERD contribution page with latest information.
=> updated technerd contribution page

pages/op-token/superchain-revenue-explainer.mdx
=> Update heading format in superchain-revenue-explainer.mdx
