ethereum-optimism/community-hub

src/.vuepress/config.js
src/docs/README.md
src/docs/integration.md

@kfichter @maurelian 
Added the resources to the documentation homepage. 
Had to remove the last "L1 <> L2 communication" resource since the link is now broken. 
Also, was wondering whether I should add any more repos in addition to the `optimism-monorepo`, `contracts-v2`, `smock` and `optimism-integration`?
I also renamed the "Intregrating" page to "Integration" because I think it reads better 😀

@platocrat/added resources

---

src/docs/developers/integration.md

Fixes #36.
Note:  I used the [most recent branch](https://github.com/Synthetixio/synthetix-cli/blob/165fb39ea9c4298d7193c1b7f169dfd95cc89a80/src/utils/runTx.js#L61-L72) of Kevin's Synthetix reference:
```solidity
async function getRevertReason({ tx, provider }) {
const code = (await provider.call(tx)).substr(138); 
const hex = `0x${code}`;
if (code.length === '64') {
return ethers.utils.parseBytes32String(hex);
} else {
return _hexToString(hex);
}
return reason;
}
```

gotcha: Revert reasons not returned on `eth_sendRawTransaction` calls

---

src/docs/developers/integration.md

Fixed the documentation for the ports that are assigned to Layer 1 and Layer 2 when starting a local node.
When using the https://github.com/ethereum-optimism/optimism-integration repo - and running (the famous) `./up.sh` - the documentation says that the OVM will run on `9545` and that layer 1 will run on `8545`
In actual fact - the OVM starts on `8545` and layer1 starts on `9545`

fix port assignment docs layer2 / layer1

---

src/docs/developers/integration.md

Update methods name to be the same as the referenced code in the links

Fix OVM_L1ETHGateway methods names in Bridging L1 and L2 section

---

src/docs/developers/integration.md

Added a notice that reminds users that the bridge and message passing contracts are pre-deployed on Kovan testnet and Mainnet.

update: bridge and messaging passing notice

---

src/docs/developers/integration.md

This is a bit of a longer diff.
Lots of changes to update the integration docs so that it has a more coherent structure.
Essentially, added steps from the `optimism-tutorial` so that users have a clear step-by-step process when walking through the integration docs.
Also cleaned up a few things.

fix:  integration docs

---

src/docs/protocol/evm-comparison.md

Looks like there are some automatic whitespace fixes in here, but this is the only substantive change: https://github.com/ethereum-optimism/community-hub/pull/93/files#diff-56a2cd2c28444339d1f21687df48d497a48b0cf03745a35ff6e693338d489756R69

fix: update setnonce to incrementnonce

---

src/docs/README.md

Discord link leads to an "Invalid Invite" page. This corrects the link.

docs: Correct discord link

---

src/docs/developers/networks.md

WebSocket endpoins are listed with https scheme instead of wss
The current url using https scheme wont work for `WebsocketProvider`

Update scheme for websockets

---

README.md
src/.vuepress/components/Home.vue
src/.vuepress/config.js
src/docs/README.md
src/docs/developers/bridging.md
src/docs/developers/integration.md
src/docs/protocol/protocol.md
src/docs/resources/general-resources.md
src/docs/resources/protocol-readings.md
src/docs/resources/talks.md
src/docs/resources/tooling.md

Replaces old discord links with a link to https://discord.optimism.io (which will now be our permanent redirect).
**Metadata**
- Fixes #114

fix: replace discord links with redirect

---

src/docs/protocol/protocol.md

Very small fix to a missing space in the documentation.

Tiny fix to Protocol Docs to correct a missing space

---

src/faqs/README.md

Removes an outdated section from the FAQs that claimed that ETH could not be used natively.

fix: remove outdated ETH section from FAQs

---

src/.vuepress/config.js
src/docs/developers/bridge/standard-bridge.md

Updated the hub with links to the tutorial on using a custom ERC20 token on the standard bridge introduced here https://github.com/ethereum-optimism/optimism-tutorial/pull/53

Custom token tutorial updates

---

src/faqs/README.md

This addition comes from a request made by a user who reported that the expected behavior is that a user can modify the gas limit and gas price, which is unlike Optimistic Ethereum.
Thus, this PR briefly explains this unexpected behavior.

fix:  add FAQ on not changing gas price or gas limit

---

.github/ISSUE_TEMPLATE/issues.md

Fixes the likely reason why the new issue template isn't applying.

Add 'about' field to issue template

---

src/.vuepress/config.js
src/docs/developers/bridge/messaging.md
src/docs/developers/bridge/standard-bridge.md
src/docs/developers/fees.md
src/docs/developers/l2/block-time.md
src/docs/developers/l2/changeset.md
src/docs/developers/l2/contracts-2.0.md
src/docs/developers/l2/contracts.md
src/docs/developers/l2/convert.md
src/docs/developers/l2/deploy.md
src/docs/developers/l2/dev-node.md
src/docs/developers/l2/hardhat.md
src/docs/developers/l2/new-fees.md
src/docs/developers/l2/rpc-2.0.md
src/docs/developers/l2/rpc.md
src/docs/developers/l2/truffle.md
src/docs/developers/util.md
src/docs/infra/networks.md
src/docs/infra/third-party-tools.md
src/docs/protocol/evm-comparison.md
src/docs/protocol/protocol-2.0.md
src/docs/protocol/protocol-readings.md
src/docs/protocol/protocol.md
src/docs/users/fees-2.0.md
src/docs/users/fees.md
src/faqs/README.md

* Put a special notice on pages that are OVM 1.0 or OVM 2.0 specific
* Update that `ORIGIN` is now supported
* Update the mainnet white listing page
* Update the new fees with the completed code snippet
* Update for OVM 2.0:
* contracts.md
* users/fees.md
* protocol.md
* rpc.md
Closing: INT-179, INT-178, INT-177, INT-176, INT-126, INT-133, INT-138, INT-134

20210923 changes

---

src/docs/users/getting-started.md

In the current version, the links for Gemini and Binance exchanges (in the depositing-assets section) appear in brackets next to their names; Unlike Coinbase, which name is used as a button.
I propose a little change that turns all exchanges names into links that lead to its corresponding exchange.
**Metadata**
- Fixes [getting-started/depositing-assets in the User Docs](https://community.optimism.io/docs/users/getting-started.html#depositing-assets)
- ![image](https://user-images.githubusercontent.com/67139425/135342486-ddf11b6c-8531-42c5-9b36-8fb66e7975b3.png)

Turn Gemini and Binance name's into buttons at 'Getting Started with Optimistic Ethereum' in the User Docs.

---

lst
src/docs/developers/bridge/messaging.md
src/docs/developers/fees.md
src/docs/developers/l2/dev-node.md
src/docs/developers/util.md
src/docs/infra/networks.md
src/docs/protocol/evm-comparison.md
src/docs/protocol/protocol.md

Instead of going to the `develop` branch (soon to be overwritten by OVM 2.0 code), they now go to https://github.com/ethereum-optimism/optimism/tree/ef5343d61708f2d15f51dca981f03ee4ac447c21

OVM 1.0 contract code refs to a specific commit

---

src/docs/developers/bridge/messaging.md
src/docs/developers/bridge/standard-bridge.md
src/docs/developers/l2/block-time.md
src/docs/developers/l2/changeset.md
src/docs/developers/l2/contracts-2.0.md
src/docs/developers/l2/convert-2.0.md
src/docs/developers/l2/deploy.md
src/docs/developers/l2/dev-node.md
src/docs/developers/l2/future.md
src/docs/developers/l2/new-fees.md
src/docs/developers/l2/rpc-2.0.md
src/docs/developers/l2/tooling-2.0.md
src/docs/developers/talks.md
src/docs/developers/tutorials.md
src/docs/developers/util.md
src/docs/infra/monitoring.md
src/docs/infra/networks.md
src/docs/protocol/evm-comparison.md
src/docs/protocol/protocol-2.0.md
src/docs/protocol/protocol-readings.md
src/docs/protocol/sequencing.md
src/docs/pub-goods/talks.md
src/docs/users/deposit.md
src/docs/users/fees-2.0.md
src/docs/users/getting-started.md
src/docs/users/metamask.md

Removes the OVM 2.0 announcements and removes "in 2.0" from titles that had it.

feat: remove 2.0 announcements and titles

---

src/.vuepress/config.js
src/docs/protocol/challenges.md

Renames "Fraud Proofs" to "Transaction Challenges" (we really need to do this consistently everywhere). Also updates the disclaimer at the top of the page to be more explicit.

feat: rename and update tx challenge page

---

src/docs/developers/bridge/messaging.md

Fix the typo in developer doc
**Metadata**
- Fixes #289

Fix typo in CrossDomainMessenger documentation

---

src/docs/developers/l2/dev-node.md

Remove OVM 1.0 docker image and update the correct branch of OVM 2.0
**Metadata**
- Fixes #295 
- Fixes #296

Remove OVM v1 reference and update branch name of OVM v2

---

src/docs/developers/l2/new-fees.md

Not only were the inputs to the L1 security fee wrong, the formula itself was wrong. It needs to take into account things such as the additional bytes of RLP encoding the transaction, the signature, etc. - so I decided to remove it.

Removed the incorrect formula

---

src/.vuepress/theme/components/PageMeta.vue
src/docs/contribute/README.md

Add a dedicated page for providing a direction to external contributors. This is intentionally mostly the same as the first section of the [Contributing guidelines](https://github.com/ethereum-optimism/optimism/blob/3174f034da022ac7ebcfde4ebd08961e377b43c3/CONTRIBUTING.md) to keep guidelines consistent.
Also updates footer 'Contribute to Optimism' link to navigate to the monorepo contribute section
**Metadata**
- Fixes INT-382

Add getting involved section content

---

src/docs/useful-tools/networks.md

As suggested on Discord. The old addresses were pre-regenesis, IIRC.

Fixed the link to contract addresses

---

src/docs/how-optimism-works/README.md

This PR changes the word "legible" to "comprehensible" in the Introduction.
The word "legible" means "clear enough to read". Replacing it with "comprehensible" is better. The word "accessible" would have also worked but it appeared in the previous sentence.

Change "legible" to "comprehensible"

---

src/docs/developers/build/dev-node.md

Command being used to start the dev node when built from source was incorrect. This PR fixes it.

fix: update dev node build and start commands

---

src/docs/developers/bridge/standard-bridge.md
src/docs/developers/tutorials.md
src/docs/protocol/protocol-2.0.md

Decommission the [Standard bridge - standard token tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token) in favour of the much simpler guide [here](https://community.optimism.io/docs/guides/token-dev/)

Decommission the standard token tutorial in favour of the guide

---

src/docs/developers/bridge/messaging.md

Closing: #352 
Closing: ori/int-538-l1-gas-burned-is-gone
Closing: INT-538
Also added:
1. The amount of gas burned isn't proportional to `gasLimit`, but `gasLimit - freeGas`
1. How to get the values of the parameters

Added the fact that L1 gas burned is gone

---

src/docs/useful-tools/faucets.md

Even though Paradigm's Multifaucet is amazing I believe some devs can't use it if they don't have `twitter` so I created this simple faucet that uses `github` for authenicating. You can check the project here https://github.com/tonykogias/optimism-faucet
I think it's worth adding it to the faucet list on the community website.

feat: add new testnet faucet

---

.github/ISSUE_TEMPLATE/bridge-bug.yml

Adds an issue template for users to report bugs they encounter on the OP gateway. 
This will be used temporarily until we have a more robust reporting system set up.

issue template for bug reports

---

src/docs/developers/bridge/standard-bridge.md

Broken Link:
Under `Bridging L1 and L2` > `Using Standard Token Bridge` > [Withdrawing ERC20s](https://community.optimism.io/docs/developers/bridge/standard-bridge/#withdrawing-erc20s) 
the link `[L1 ⇔ L2 deposit-and-withdraw example (opens new window)]` gives "404: The 'ethereum-optimism/optimism-tutorial' repository doesn't contain the 'l1-l2-deposit-withdrawal' path in 'main'."
Fix: 
Links to: https://github.com/ethereum-optimism/optimism-tutorial/tree/main/l1-l2-deposit-withdrawal
Corrected link: https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-bridge
**Metadata**
- Fixes #423

Fix L1 to L2 Deposit Example Link

---

src/docs/guides/bridge-dev.md

Fixing the link to cross-chain communication tutorial. There was an outdated link to tutorial

Fix the broken link

---

src/docs/useful-tools/networks.md

Added Pocket Network to the list of public RPC endpoints
Added Pocket Network to the list of public RPC endpoints
Pocket Network is a decentralized, multi-chain RPC protocol

Update networks.md with Pocket Network public RPC endpoint

---

src/docs/developers/bedrock.md
src/docs/useful-tools/faucets.md
src/docs/useful-tools/networks.md

1. Update that https://optimismfaucet.xyz/ now works with Optimism Goerli
2. Remove the statement that Optimism Goerli is very much work in progress, because it's now supported by a lot more infrastructure.
3. Update that https://app.optimism.io/bridge now works with Optimism Goerli.
Closing: DOCS-633

feat(faucets): Update https://optimismfaucet.xyz to Goerli

---

src/docs/developers/bridge/standard-bridge.md

Fix: typo in standard-bridge.md

---

src/docs/governance/airdrop-1.md

The link to Optimism's Dune dashboard points to the old account.

fix: update broken link to dune dashboard

---

src/docs/developers/build/dev-node.md
src/docs/developers/build/run-a-node.md
src/docs/guides/cex-dev.md
src/docs/guides/wallet-dev.md
src/docs/useful-tools/networks.md
src/docs/useful-tools/providers.md

We want people to go to https://www.alchemy.com/optimism, which then redirects them to https://www.alchemy.com/layer2/optimism? .
Note that there are other Alchemy links that are deeper, which this commit does not change

feat(*): Replaced Alchemy links to affiliate ones

---

src/docs/developers/bridge/messaging.md

A function declaration keyword was missing, added in several places.
**Tests**
Not required

Docs fix: added function declaration keyword

---

src/docs/useful-tools/networks.md

As requested by Shelley from Alchemy:
https://optimism-workspace.slack.com/archives/C01R0SBFYHJ/p1669158128126449

fix(networks): Fix a developer tip to be not all headline

---

src/docs/developers/bedrock-temp/upgrade-guide.md
src/docs/developers/bedrock.md
src/docs/developers/bedrock/README.md

Temporary fix for https://dev.optimism.io/optimisms-goerli-testnet-is-migrating-to-bedrock/, because it's vacation and I'm not sure if there's anybody authorized to edit it available.

fix(bedrock): Create links for dev blog

---

src/docs/developers/bedrock/upgrade-guide.md

Adds specific information for day-of Optimism Goerli and Optimism Mainnet Bedrock upgrades.

feat(bedrock) - add Goerli and Mainnet specific upgrade info

---

src/docs/developers/bedrock/upgrade-guide.md

Replacing #590
Instead of changing the directory, this fix adds the file extension (`.md`) to achieve the same goal.

fix(upgrade-guide): Fix the links

---

src/docs/developers/bedrock/bedrock.md

fixes incorrect EIP1559 RPC information 
eth_maxFeePerGas is not a real thing - removed from the docs.
eth_feeHistory is added with EIP1559, but not included in the docs.

fix incorrect EIP1559 RPC information

---

src/docs/governance/retropgf-2.md

- Renames "Project sign-up" to "Project opt-in" to help understanding 
- Replaces "Gitcoin Grants Hub" with "RetroPGF Application manager"
- Adds context to the Nominations process
- Updates notes on voting process
- Remove mention of "individuals" for funding applications. Instead outline that "project" captures both groups and individuals. 
- Add Collections to Nominations

Updated RetroPGF Round 2 doc

---

src/.vuepress/config.js
src/docs/developers/bedrock/metrics.md
src/docs/developers/bedrock/node-operator-guide.md

Both of these updates are in response to user feedback. Metrics are important for debugging + monitoring purposes, and folks were provisioning too few resources for `op-geth`.

Add metrics guide, add Bedrock system requirements

---

src/docs/developers/bedrock/bedrock.md

Adds information to specify that it is recommended to add a buffer to your gas limit for all deposit transactions. Also clarifies that the OptimismPortal should only be used to avoid the sequencer, and not for general message passing.

Add additional deposit information for bedrock

---

src/docs/developers/bedrock/public-testnets.md

Remove upgrade rehearsal testnet as it is no longer relevant
Fix copy to clarify that we already upgraded Optimism Goerli to Bedrock
Update legacy datadir URL to the archival datadir (the previous link gives legacy-geth a full node datadir, which makes it useless for its single use case of processing archival requests)

Update bedrock public testnets page

---

src/docs/governance/README.md

Unlinks token-house.md from "Token House" and relinks to "Collective" as references info applicable to entire Collective

Unlink and relink token-house.md

---

src/docs/useful-tools/providers.md

This PR adds [Chainnodes](https://www.chainnodes.org/) to the provider list.
**Tests**
It's just an update of a Markdown file.
Chainnodes is a Web3 infra provider and provides access to Optimism and Optimism Goerli archival nodes.

feat: add chainnodes to provider list

---

src/docs/useful-tools/monitoring.md

Hey there - when looking for block explorers for Optimism, I found Alchemy's page useful as it provided code snippets and links to multiple popular ones, alongside respective information. The current Optimism article is limited as only has two options but this link will provide developers with more options.

Added Link to Additional Block Explorers

---

src/docs/developers/bedrock/differences.md

Updating to track with our current config: https://github.com/ethereum-optimism/k8s/blob/master/bedrock-k8s/overlays/goerli-prod/config.yaml#L21
I checked with Proto on this.

fix: docs on L1 Block data confirmation depth

---

src/docs/developers/build/dev-node.md

Now that we have OP Stack, a devnode is just an OP Stack with a locally running L1 (Ganache, for example).

feat(dev-node): Direct people to OP Stack

---

src/docs/governance/attestation-station.md

Feedback from Hackathons is that designating like social vs trusted attestations are causing confusion

Remove ambiguous wording

---

src/docs/developers/bedrock/differences.md

As requested in https://oplabs-pbc.slack.com/archives/C01R0SBFYHJ/p1680201565524699?thread_ts=1680195899.080699&cid=C01R0SBFYHJ

fix(bedrock/differences): Made it clear safe blocks can be reorged

---

src/docs/governance/attestation-station.md

Add Sismo and subgraph as Attestation station integrations.
The integration allows anyone to use any attestations as a data source to create new identity sets and build more robust, trustworthy identities.
The subgraph is used to query in the data provider. 
There's a pending PR on Sismo to update the docs to include the AttestationStation Provider. 
https://github.com/sismo-core/sismo-docs/pull/3
The provider itself can already be used though.

Add Sismo and subgraph as Attestation station integrations

---

src/docs/developers/build/differences.md

With pre-eip-155 Transactions:
We need to communicate clearly to developers in documentation that pre-EIP155 transactions should largely be avoided (and why), but also outline how to send pre-EIP155 transactions if desired. We do this in our documentation [here](https://community.optimism.io/docs/developers/build/differences/#pre-eip-155-support) already. I'm not sure why we had this seperate section saying that support is "removed" when it is actually not.
This was causing confusion with Base.

Remove incorrect info about pre-EIP-155 transactions on Optimism

---

src/docs/protocol/txn-flow.md

While testing out the OP devnet, I was unable to use the queries `cast block finalized number` and `cast block safe number`, as they returned errors. I have saved logs in this [Gist](https://gist.github.com/jcstein/678bba67617b8ce6e58413c87846af3b)
I found that removing `number` from the queries helped me send these queries successfully. Which can be seen in a [Gist](https://gist.github.com/jcstein/06ac479927131762269c0dbacd404ce2).
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

fix: cast commands

---

src/docs/protocol/README.md

The Optimism Foundation runs the sequencer, not OP Labs PBC.
**Tests**
NO tests are needed.
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

Update Sequencer owner from "Optimism PBC" to "Optimism Foundation".md

---

src/docs/protocol/README.md

Updating the Optimism Spec Repository from the archived version to its new home on the Optimism Monorepo.
**Tests**
n/a docs update
**Invariants**
n/a docs update
n/a docs update
**Metadata**
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

Update Optimism Spec Repository Link

---

src/docs/useful-tools/networks.md

The existing link only worked until a different package was released from the monorepo.

feat(networks): Fix the `op-node` link

---

src/docs/developers/build/run-a-node.md

The [Running an OP Mainnet or testnet - Scripts to start the different components](https://community.optimism.io/docs/developers/build/run-a-node/#scripts-to-start-the-different-components) had two `--datadir` flags specified. In the instructions above, it tells the user to make a `datadir` directory in the root directory of `op-geth`. I left the flag that points to this directory that the user has made before this step.
**Tests**
n/a
**Metadata**

removing extra datadir flag

---

src/docs/useful-tools/debugging.md
src/docs/useful-tools/explorers.md
src/docs/useful-tools/monitoring.md

Blockscout just released v5.2.0. This is a new UI and a new URL for their explorer.
**Tests**
n/a documentation update
I added clarification on `src/docs/useful-tools/explorers.md` that they have verified contract source code, the ability to interact with it and tx information on _testnet_. The op mainnet links are not showing errors.
**Metadata**
- Fixes DEVRL-1013

updating blockscout urls

---

src/docs/identity/atst-v0.md

This SDK has been removed in https://github.com/ethereum-optimism/optimism/pull/5973, remove references to it.
Also, this PR freezes the link to the contract source code.
Closing: DEVRL-993

feat(atst-0): Remove SDK references

---

src/docs/developers/bedrock/node-operator-guide.md

https://community.optimism.io/docs/developers/bedrock/node-operator-guide still has a bedrock only notice, remove it.
Closing: DEVRL-990

feat(node-operator-guide): Remove Bedrock only notice

---

src/docs/developers/build/json-rpc.md

Daisy-chain is an old component, which was part of the Bedrock design but got removed at some point between Goerli and mainnet (IIRC).
Closing: DEVRL-989

feat(json-rpc): Remove daisy chain reference

---

src/.vuepress/config.js
src/docs/developers/releases.md

feat(releases): Replace old page with link to github

---

src/docs/developers/known-issues.md

feat(known-issues): Add EIP 1559 stuck tnx issue

---

src/.vuepress/config.js

Fix `Developer Docs > SDK > Contracts` sidebar link

fix(sidebar): Move SDK > Contracts to new link

---

src/docs/sdk/js-client.md

Closing: [DEVRL-1051](https://linear.app/optimism/issue/DEVRL-1051)

feat(js-client): Add OP Chain support

---

src/docs/developers/build/transaction-fees.md

- Update with the additional information from the bedrock wallet upgrade guide
- Remove "gas price too high" and "gas price too low" errors
Closing: [DEVRL-1001](https://linear.app/optimism/issue/DEVRL-1001)

feat(txn-fees): Update to bedrock

---

src/.vuepress/theme/components/Anchor.js
src/.vuepress/theme/components/PageMeta.vue
src/docs/biz/README.md
src/docs/governance/airdrop-1.md

Updating Public facing Marketing & Inbound links
I removed one form link for suggestions on sybil resistance suggestions in the airdrop page. Our updated forms don't fit here.
**Metadata**
- Fixes #DEVRL-1133

removing references to old forms and adding updated form links

---

src/docs/developers/bridge/messaging.md

These docs are out of date and should reference the bedrock system. They still reference the legacy system.

docs: update messenger links

---

src/docs/developers/build/transaction-fees.md

DevX added a[ new JS package](https://github.com/ethereum-optimism/optimism/tree/develop/packages/fee-estimation) specifically for fee estimation, which is size and performace optimized. Adding this and ongoing work to the docs for easy discovery. 
Note, this was one of our most cited developer pains from last quarter.
This will be coming natively in ethers, wagmi, and web3.js. I know we haven't called out specific tools in the past, but opening the conversations here and wondering what y'all think is valuable!
**Metadata**
- Part of https://github.com/ethereum-optimism/devx/issues/19

update: add fee-estimation package to dev docs

---

src/docs/developers/build/run-a-node.md

Currently, datadir flag is duplicated in the document. The correct one is ./datadir as per prior steps.
**Tests**
No test needed for a simple document change
https://community.optimism.io/docs/developers/build/run-a-node/#

Fix duplicated datadir in "Running an OP Mainnet or testnet node"

---

src/docs/developers/bedrock/wallet-upgrade.md

bloop was too lazy to open a text editor

update: added recommended values to wallet guide

---

src/docs/developers/bedrock/wallet-upgrade.md
src/docs/developers/build/transaction-fees.md

We've been seeing txs stuck in the mempool due to base fee spikes; we've also been seeing users over pay on priority fees. This PR adds recommended values for both.
In addition to merging this change, we should also push this recommendation to wallets!
**Metadata**
- Fixes https://www.notion.so/oplabs/EXTERNAL-Fixing-TXs-stuck-in-mempool-4f11cec8769e4ad287b1f1d1f0e75c4f?pvs=4
- Task in devX push to get wallets and libraries to update OP Chain values https://github.com/ethereum-optimism/devx/issues/43

update: add recommended fee values to tx and wallet docs

---

src/docs/governance/get-a-grant.md

Fixing collective intents link which currently directs users to a comment in the forum post, even though it should link to the main post itself
Also fixing a link formatting error [Mission](...)s --> [Missions](...)
**Tests**
n/a
n/a
**Metadata**
n/a

Fix link to Collective Intents forum post

---

src/docs/developers/bridge/standard-bridge.md

Adding native USDC and USDC.e contract addresses and a warning about mixing them up when using `depositERC20` and `depositERC20To`.
**Tests**
n/a
**Metadata**
- Fixes https://github.com/ethereum-optimism/developer-support/issues/144

adding information about native USDC

---

src/docs/useful-tools/explorers.md

Tied to issue #155, https://github.com/ethereum-optimism/developer-support/issues/155
Updates two existing links and add more details to paragraph (similiar layout of etherscan section immediately below). 
**Tests**
checked links provided 
Blockscout wants to showcase their full offering on OP Mainnet, similar to Etherscan's writeup
**Metadata**
- Fixes #[Link to Issue](https://github.com/ethereum-optimism/developer-support/issues/155)

Update blockscout paragraph on explorers.md

---

src/docs/developers/bridge/standard-bridge.md

Adding contract address reference in the bridging documentation so developers don't go looking on etherscan/monorepo and find the implementation addresses.
**Tests**
**Metadata**

adding contract address reference

---

src/docs/developers/build/run-a-node.md

I have run this script with the latest version of Foundry and got an error.
```
error: unexpected argument 'number' found
```
And I found that ETH_RPC_URL is not used.
So, I propose a fix to the above problems.
cast 0.2.0 (ae89c92 2023-09-15T00:16:50.567420396Z)

Fix speed test script to be compatible with latest foundry

---

src/docs/governance/airdrop-1.md

The airdrop 1 address csv file names were updated, but they were not updated in the docs.
**Tests**
**Metadata**

fixing broken link

---

src/docs/useful-tools/providers.md

BlockPI is a mainstream RPC provider, handling nearly 1 billion RPC requests per day. OP's RPC requests have a significant proportion. I believe we are qualified to be included in this document. Thanks!
**Tests**
Just simply adding BlockPI in the RPC provider list.
None
**Metadata**
- Fixes #[Link to Issue] None

Add Blockpi to - Node & API Providers

---

src/docs/governance/economics.md

There is a notice in the OP Economics page saying that "OP Airdrop #1 is now available to claim". This information is however no longer correct since unclaimed OP from Airdrop 1 was sent directly to addresses eligible to claim on Sep 15.
This PR removes the section with the outdated information.
**Tests**
**Metadata**

Remove outdated Airdrop #1 notice

---

src/docs/governance/existing-delegate.md

This PR deletes a link to the unused # token-house-gov channel on Discord. The last post there was published in January and announced the beginning of Season 3.
Since this channel is no longer used, it is misleading to link to it and suggest that it will "help you keep up to date".
**Tests**
**Metadata**

Remove link to Discord channel that is no longer used

---

src/docs/developers/bedrock/node-operator-guide.md

Bedrock is live, removing the beta network configuration and replacing it with the mainnet sequencer url.
**Tests**
**Metadata**

removing beta network configuration

---

src/docs/developers/nodes/mainnet.md
src/docs/developers/nodes/testnet.md

Websockets provide a slightly more efficient way to communicate over the engine-api between `op-geth` and `op-node`.

updating engine api connection to ws

---

src/docs/developers/bedrock/node-operator-guide.md
src/docs/developers/nodes/testnet.md
src/docs/useful-tools/networks.md

OP Sepolia requires initialization via genesis file and special flags for `op-node` and `op-geth`. I've added this information.
**Tests**
**Metadata**
- fixes: https://github.com/ethereum-optimism/developer-support/issues/252

Op sepolia updates

---

src/docs/useful-tools/providers.md

Description
BlockPI is a mainstream RPC provider, handling nearly 1 billion RPC requests per day. OP's RPC requests have a significant proportion. I believe we are qualified to be included in this document. Thanks!
Tests
Just simply adding BlockPI in the RPC provider list.
Additional context
None
Metadata
Fixes #[Link to Issue] None

Update providers with Change name case

---

src/docs/developers/build/transaction-fees.md

Re-Add `noncalldata_gas` given feedback from teams trying to estimate.
Open to how this should best be calculated, since the current formula will understate the actual l1_gas_used field.
**Tests**
**Metadata**

Add handling for "noncalldata_gas" to the L1 data fee calculation

---

src/docs/protocol/2-rollup-protocol.md

Fixes typo in docs, h/t @trianglesphere 
**Tests**
No tests since this just fixes a typo
N/A
**Metadata**
N/A

fix typo in 2-rollup-protocol.md

---

src/docs/developers/bridge/messaging.md
src/docs/useful-tools/networks.md

Fix the URL for deployment contracts in the:
- https://community.optimism.io/docs/developers/bridge/messaging/#communication-basics-between-layers
- https://community.optimism.io/docs/useful-tools/networks/#op-mainnet
**Tests**
Docs update
**Metadata**

deployment contracts url fix

---

src/.vuepress/theme/components/Anchor.js
src/.vuepress/theme/components/PageMeta.vue
src/docs/biz/README.md

Updating the general airtable connect form links
**Tests**
**Metadata**

fix: broken airtable form link

---

src/docs/protocol/README.md

I found it more useful for users/doc reviewers to land into (https://github.com/ethereum-optimism/optimism/tree/develop/cannon) and get direct information about the onchain MIPS instruction emulator than to drive them towards a repo that is now archived "(https://github.com/ethereum-optimism/cannon/)" and won't contain the latest docs and development information in the future.
Please review and approve this PR if this also makes sense to other code owners for this project.

Update README.md with the new "cannon" links from the Monorepo

---

src/.vuepress/config.js

Update config.js with airdrop 4

---

src/docs/developers/nodes/testnet.md

fix a typo: `funadmentally`->`fundamentally`

chore: fix typos

---

pages/citizens-house/citizen-house-overview.mdx

"tme" corrected to "**time**" in the sentence.

Typo Update citizen-house-overview.mdx

---

lychee.toml
pages/404.mdx
pages/500.mdx
pages/contribute/contribution-path/ambassador-req.mdx
pages/contribute/contribution-path/govnerds.mdx
pages/identity/_meta.json
pages/identity/about-attestations.mdx
pages/identity/applications.mdx
pages/identity/contracts-eas.mdx
pages/identity/identity-overview.mdx
pages/identity/individuals.mdx
pages/identity/organizations.mdx
pages/identity/overview.mdx
pages/identity/project-and-individual-identity.mdx
pages/identity/projects.mdx
pages/identity/schemas.mdx
pages/op-token/airdrops/airdrop-1.mdx
pages/op-token/airdrops/airdrop-5.mdx
words.txt

This PR implements part of our navigation restructuring epic, specifically focusing on reorganizing the Identity documentation. The goal is to improve content organization by moving technical content to the appropriate sections and relocating community-focused content to community.optimism.io.
- Moved EAS Contract documentation to OP Stack predeploys section for better technical context
- Relocated remaining identity content to community.optimism.io 
- Added appropriate redirects to maintain link integrity
- Removed the Identity subdirectory on dev docs
- Set up redirects for all moved pages
- Updated internal cross-references
**Tests**
**Metadata**
- Fixes - https://github.com/ethereum-optimism/devrel/issues/370

Moved identity files
